name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
   branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.5.7
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "test-my-project-app" #Must be unique in Heroku
          heroku_email: "ignaciojonas@gmail.com"
