name: Dusk Tests
on:
 push:
   branches: [ master ]
 pull_request:
   branches: [ master ]
jobs:
 dusk-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
          image: mysql:5.7
          env:
              MYSQL_ALLOW_EMPTY_PASSWORD: yes
              MYSQL_DATABASE: laravel
          ports:
              - 3306:3306
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      APP_URL: "http://127.0.0.1:8000"
      USE_SELENIUM: false
    steps:
      - name: Verify MySQL connection from host
        run: |
          sudo apt-get install -y mysql-client
          mysql --host 127.0.0.1 --port 3306 -uroot -e "SHOW DATABASES"
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Copy .env.dusk.local
        run: php -r "file_exists('.env') || copy('.env.example', '.env.dusk.local');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Upgrade Chrome Driver
        run: php artisan dusk:chrome-driver `/opt/google/chrome/chrome --version | cut -d " " -f3 | cut -d "." -f1`
      - name: Run Migrations
        run: php artisan migrate
      - name: Run Laravel Server
        run: php artisan serve
      - name: curl to localhost
        run: curl localhost:8000
      - name: Start Chrome Driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1
      - name: Change permissions to dusk
        run: chmod -R 0755 vendor/laravel/dusk/bin/
      - name: Run Dusk Tests
        run: php artisan dusk
